services:
  kagane:
    image: ghcr.io/astral-sh/uv:alpine
    container_name: kagane-drm
    command: uv run main.py
    volumes:
      - ./main.py:/main.py
      - ./device.wvd:/device.wvd
    ports:
      - "9191:9191"
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8191:8191"
    restart: unless-stopped
networks:
  default:
    driver: bridge
